### ISSUE TITLE
"This expression is not constructable" error when consuming the ConfigIniParser from typescript

### ISSUE THREAD

**Issue by dcermak** [shangerxin/config-ini#12]
I have tried to fix the typescript declarations in #11, but apparently the export in: https://github.com/shangerxin/config-ini/blob/fcda3105bb1ed61b3a0152b9a2bcf9298ce2a4b1/config-ini.d.ts#L142
is not correct. When I try to use the class in typescript code:
``` ts
import { ConfigIniParser } from "config-ini-parser";
const parser = new ConfigIniParser();
```
then typescript complains with:
```
src/account.ts:96:22 - error TS2351: This expression is not constructable.
  Type 'ConfigIniParser' has no construct signatures.

96   const parser = new ConfigIniParser();
                        ~~~~~~~~~~~~~~~
```
Unfortunately I have been unable to solve this myself. If anyone has an idea, any pointers would be greatly appreciated.

**Comment by shangerxin** [comment]
Thank you  @dcermak  for the feedback. I will check and get back to you soon.

**Comment by shangerxin** [comment]
Hi @dcermak ,

The issue is checked. It seems currently we only support commonjs module type for typescript. Here is an example content of tsconfig.json 

```
{
	"compilerOptions": {
		"module": "commonjs",
		"noImplicitAny": true,
		"removeComments": true,
		"preserveConstEnums": true,
		"sourceMap": true
	},
	"include": ["./**/*"]
}

```
Please also make sure add the dependency for typescript for your nodejs project in case it is created manually. There should be a dependencies field in the package.json

```
	"dependencies": {
		"@types/node": "^14.6.2",
		"config-ini-parser": "^1.3.4",
		"typescript": "^4.0.2"
	}

```

Then the type definition file can be referenced with the code. Make sure modify the reference path to point to the right location of the file:

```
///<reference path=".\\node_modules\\config-ini-parser\\config-ini.d.ts"/>

const ConfigIniParser = require("config-ini-parser").ConfigIniParser;

let p = new ConfigIniParser();
try {
	p.addSection("abc");
} catch (e) {
	if (e == ConfigIniParser.Errors.ErrorDuplicateSectionError) {
		console.error("Add duplicated section");
	}
}
```

Best regards, 
Edwin

**Comment by shangerxin** [comment]
Hi @dcermak ,

The definition file is updated to support the import statement. Please update the npm package and try again. Thanks for your feedbacks again!

Best regards, 
Edwin

**Comment by shangerxin** [comment]
Hi @dcermak , It's my pleasure. :)
