### ISSUE TITLE
Shouldn't `sectionName` argument to `get` be optional?

### ISSUE THREAD

**Issue by henrebotha** [shangerxin/config-ini#13]
[In the types file](https://github.com/shangerxin/config-ini/blob/b6bd0f234391ae1eb7fca130cccd0dcb0e44d20a/config-ini.d.ts#L37), `get` has `sectionName` as a required argument.

However, the docs say:

> If there is no section supplied for the options then a default section will be used

So shouldn't `sectionName` be optional in the types (i.e. `sectionName?`)?

**Comment by shangerxin** [comment]
Nice catch! I will update the type definition file. Thank you.

**Comment by shangerxin** [comment]
Hello @henrebotha ,

After check the code and document, base on the current design, the secionName and optionName are passed sequencially to the get function. If we change the parameter sequence, it will be a breaking changes. The test case to verify this feature is passed the value null. 
Do you think only update the type define document is OK to let it accept null?

Best regards, 
Edwin

**Comment by shangerxin** [comment]
I will add the new function to provide a convience access method for the options in the default section. Then we can close the issue. Welcome to know your comments. Thank you.

Best regards, 
Edwin

**Comment by shangerxin** [comment]
The version is updated to 1.5.0 and several relative methods are added. The isuse will be closed.
