### ISSUE TITLE
trim issue

### ISSUE THREAD

**Issue by basaran** [shangerxin/config-ini#14]
Hello, could you change this line:

```
value = line.substr(assignPosition + assignIdentifierLength);
```

to

```
value = line.substr(assignPosition + assignIdentifierLength).trim();
```

Otherwise, it's keeping spaces in values. Thank you for the package.

**Comment by shangerxin** [comment]
Hi basaran,

Thank you for the feedbacks. I will identify the issue and update the package.

Best regards, 
Edwin

**Comment by shangerxin** [comment]
Hi basaran, 

There is no code contain the specified line. Could you please double check again. If there is anything need I do please let me known. This issue will be closed temporarly. 

Best regards, 
Edwin
