### ISSUE TITLE
Can't use false, 0 or '' as default value.

### ISSUE THREAD

**Issue by flaviospagnuolo** [shangerxin/config-ini#16]
If I use any of those values as the third parameter for the get method, it throws errorNoOption.
Maybe you should replace "if (defaultValue)" with "if (defaultValue === undefined)".

**Comment by shangerxin** [comment]
Hi @flaviospagnuolo ,

Nice catch. The relative code is updated. Please check the latest version 1.5.2. Now we support  false, 0, null or '' as default value Thank you!

Best regards, 
Edwin
