### ISSUE TITLE
parse ini that have key without value throw error

### ISSUE THREAD

**Issue by RGdevz** [shangerxin/config-ini#18]
ini that have something like 

`[mysqlhotcopy]`
`interactive-timeout`

throw error

**Comment by shangerxin** [comment]
Hey @RGdevz ,

The key/value is invalid. Please check the definition of the ini file at [https://en.wikipedia.org/wiki/INI_file](https://en.wikipedia.org/wiki/INI_file).

The option required at least for one "=" character before the empty value. Then the parser will return the value as an empty string ("") for the key. 

Thank you for the feedback. The issue will be closed. 

Best regards, 
Erxin (Edwin)
