### ISSUE TITLE
valid config gives error

### ISSUE THREAD

**Issue by serj-p** [shangerxin/config-ini#2]
hello, there is an issue with the module

[SMS_DC_Countries]
1=[ "1", "2" ]
61=[ "1", "2" ]
44=[ "1", "2", "16" ]
31=[ "16"]
32=[ "16"] ;;  <-- this gives error {name: "ConfigIniParser Error", message: "Found duplicated section in the given ini file"} what is not section but value
353=[ "1", "2", "16" ]
420=[ "1", "2", "16" ]
421=[ "1", "2", "16" ]

please help

**Comment by shangerxin** [comment]
Thank you for the update. I will check the and update the result. Sorry for the late response.

**Comment by shangerxin** [comment]
Defect raised and fix will be committed

**Comment by shangerxin** [comment]
Please check the result from the latest artifacts. Thank you very much!
