### ISSUE TITLE
Error parsing section header with spaces

### ISSUE THREAD

**Issue by foreignbyproxy** [shangerxin/config-ini#3]
I'm trying to parse a php.ini file but the package is throwing an error when it reaches section headers with whitespace between the characters. For example, the section header "[CLI Server]" will throw an error.

The _sectionRegex regex expression does not cover this case. Setting the _sectionRegex variable to /^\[([^\]\r\n]+)]/ has solved this problem for me.

**Comment by shangerxin** [comment]
Thank you for the feedback. Do you want to create a pull request for helping fix this issue or let me upgrade the library by myself?

**Comment by shangerxin** [comment]
Fix is committed. Please pull the latest version to fix the issue. Thanks again.
