### ISSUE TITLE
Found duplicated section in the given ini file

### ISSUE THREAD

**Issue by shmox75** [shangerxin/config-ini#6]
I have my ini file which I created manually containing only this
[DB]

```
const iniContent = fs.readFileSync(filePath, 'utf-8'); console.log(iniContent); //this gives [DB]
parser.parse(iniContent);
```

This gives me error: ConfigIniParser Error Found duplicated section in the given ini file

How is it possible ? I've tryied many delimitters (I am on windows) like \n or \r\n

EDIT:

It's my fault I've called .parse method two times sorry

**Comment by shangerxin** [comment]
Got it. May be I can improve the logic to give more intuitive message to prevent similar issues.

**Comment by shangerxin** [comment]
@shmox75 An more intuitive error message is added when call the parse method multiple times for the same intsance. The issue will be closed.
