### ISSUE TITLE
Two points ":" causing error 

### ISSUE THREAD

**Issue by shmox75** [shangerxin/config-ini#7]
I have ini file

```
[FOLDERS]
DATA_ROOT_FOLDER=C:\wamp64\www\MyElectronAngularWorksFinal
```

When  I do

`parser.get('FOLDERS','DATA_ROOT_FOLDER')`

I got [ConfigIniParser Error]: The specify option not found

When I remove the : string it works

**Comment by shangerxin** [comment]
Got it. Thanks for the feedback I will check and fix this issue soon

**Comment by shangerxin** [comment]
@shmox75 The issue is fixed. Please check the latest version. Thank you.
